### ISSUE TITLE
Close gocode on Sublime Text exit

### ISSUE THREAD

**Issue by syncore** [ironcladlou/GoTools#120]
On Windows, gocode.exe continues to run even after Sublime Text closes. Is there some kind of workaround for this?

**Comment by ironcladlou** [comment]
Gocode uses a transparent client/server model and daemonizes itself by design. I looked in the sublime API for a way to implement a plugin destructor or hook into the shutdown sequence or window close event, but nothing's standing out at me at the moment. Running `gocode close` will shut down the daemon.

The Sublime forums are currently down; I'll do some digging to see what our options are.

**Comment by syncore** [comment]
Thanks! It's not really a huge deal, I mean gocode barely uses any resources and I currently have a key combination bound to close gocode (I just need to remember to press it)

**Comment by ironcladlou** [comment]
Looks like there's an upstream issue to support callbacks on Sublime close: https://github.com/SublimeTextIssues/Core/issues/10

**Comment by ironcladlou** [comment]
Seems unlikely this will ever be fixed.
