### ISSUE TITLE
More commands 

### ISSUE THREAD

**Issue by ullutau** [ironcladlou/GoTools#90]
Commands for 'generate', build&run (compiled executable, not 'go run'), 'kill' will be useful, especially if we can run built executable redirecting it's output to panel. I think clickable stack traces in output panel will be useful too.

**Comment by ironcladlou** [comment]
Thanks for the feedback. Let's break this down into discrete features:

1. `go generate`: I don't use this day to day and so don't have a good idea of the usage patterns and what a Sublime integration might look like. Do you have any ideas on how it might work from and end-user's perspective?
2. `go run` (and output redirection): I'm hesitant to start introducing terminal-like features and non-backend process management. Can you elaborate more on how that would improve your workflow over using a terminal for running programs?

Did you find some example where a stack trace generated from a unit test wasn't clickable within the output panel? I seem to remember finding some cases where I had output that wasn't clickable (due to relative filenames in the output), but never filed a bug.

**Comment by ullutau** [comment]
1. I use it every day (example: generating db related code), and think the behavior is calling `go generate` in current file directory and output results to panel. Example: we have project `github.com/ironcladlou/somegoproject`. Also we have `github.com/ironcladlou/somegoproject/db` with generated code for accessing database. `/db/schema.go` contains line `//go:generate dbgen --someoption`, so to generate database related code in `db` package we should call `go generate` in `github.com/ironcladlou/somegoproject/db`.

2. `go build` generates executable in current directory (if package is named `main`). I only want to run freshly built executable and see it's output in the panel, and have abilities to stop them and to click on filenames in logs on stdout and stacktraces. Tests in some cases is not enough, sometimes I need to run code for a while and analyse it's output manually during it's execution.

3. Sorry, but I can't run tests, when I issue command from GoTools build system nothing is happens, so I can't answer this question. Possible bug? Or I need to tweak something to use build system to run tests?

Question: why build system calls `go install` on every build? I have $GOPATH/bin in my path, and after few days of plugin usage I have every package's executable I build in my PATH. 

Anyway, great job, keep going! :+1:

**Comment by ullutau** [comment]
Closed by accident

**Comment by ironcladlou** [comment]
Moving the discussion about `go generate` to #110.

**Comment by ironcladlou** [comment]
>Question: why build system calls go install on every build? I have $GOPATH/bin in my path, and after few days of plugin usage I have every package's executable I build in my PATH.

The answer is selfish: GoTools is built around my own habits. :grin: 

When I'm working with Go, I like to build in Sublime, switch to my terminal, and run the thing I just built. If I didn't `go install` then I'd have an extra step. I've never not wanted to `go install`, so never added a setting. I really try to avoid adding settings because they increase the testing and maintenance burden.

Maybe someday GitHub will implement [issue voting](https://github.com/isaacs/github/issues/9)...

**Comment by ironcladlou** [comment]
>Sorry, but I can't run tests, when I issue command from GoTools build system nothing is happens, so I can't answer this question. Possible bug? Or I need to tweak something to use build system to run tests?

To get started, add `test_packages` key in your project's GoTools settings. From there you can run any of the test commands [described in the README](https://github.com/ironcladlou/GoTools/blob/master/README.md#tests).

**Comment by ironcladlou** [comment]
Regarding the ability to execute a go program after building within Sublime (outlined in https://github.com/ironcladlou/GoTools/issues/90#issuecomment-135932648), I don't think I'm going to implement this as described.

Sometimes I've really wanted something very special purpose like the go playground: run a command, get a new temporary buffer which you can then run a special command against to compile and run and get the output (no interactivity supported via stdin). I can see how that concept *might* be slightly extended to "compile and run current file".

**Comment by ironcladlou** [comment]
Closing this in favor of discrete followup issues.
